#!/bin/bash

set -euo pipefail


if command -v zsh >/dev/null; then
    sudo chsh -s $(command -v zsh) $USER
fi

### That file will allow to setup an environnement with the Devpod tool, it is automatically exectured by devcontainer
# touch /tmp/hello

echo "Hello" > /tmp/hello # Allow to test if a file has been created after the container is created
echo "set -o vi" >>  ~/.bashrc # Allow to use Vi motion in CLI

if [ ! -d "$HOME/.zsh" ]; then
  mkdir -p "$HOME/.zsh"
fi

# Check if pure is already installed
if [ ! -d "$HOME/.zsh/pure" ]; then
  git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"
fi

if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:Vehementz/dotfiles-repository.git
fi

exit 0

# source ~/.bashrc
