#!/bin/bash

set -euo pipefail


if command -v zsh >/dev/null; then
    sudo chsh -s $(command -v zsh) $USER
fi

### That file will allow to setup an environnement with the Devpod tool, it is automatically exectured by devcontainer
# touch /tmp/hello

echo "Hello" > /tmp/hello # Allow to test if a file has been created after the container is created
echo "set -o vi" >>  ~/.bashrc # Allow to use Vi motion in CLI

if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:Vehementz/dotfiles-repository.git
fi

exit 0


# source ~/.bashrc
