#!/bin/bash

### That file will allow to setup an environnement with the Devpod tool
touch /tmp/hello
touch testfile
echo "Hello" > /tmp/hello # Allow to test if a file has been created after the container is created
echo "set -o vi" >>  ~/.bashrc # Allow to use Vi motion in CLI

